apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  storageClassName: nfs-client-retain
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        # resources:
        #   limits:
        #     cpu: "250m"
        #     memory: "200Mi"
        #   requests:
        #     cpu: "250m"
        #     memory: "200Mi"
        env:
        - name: MYSQL_USER
          value: "keycloak-user"
        - name: MYSQL_PASSWORD
          value: "keycloak-password"
        - name: MYSQL_DATABASE
          value: "keycloak"
        - name: MYSQL_ROOT_PASSWORD
          value: "passer"
          # valueFrom:
          #   secretKeyRef:
          #     name: mysql-secret
          #     key: password
        ports:
        - containerPort: 3306
          name: tcp
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql-svc
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: tcp
    name: tcp
  selector:
    app: mysql
  type: ClusterIP

