apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  storageClassName: nfs-client-retain
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: mongodb
        # imagePullPolicy: IfNotPresent
        ports:
          - name: tcp
            containerPort: 27017
        resources:
          limits:
            cpu: "250m"
            memory: "200Mi"
          requests:
            cpu: "250m"
            memory: "200Mi"
        # livenessProbe:
        #   exec:
        #     command:
        #       - mongo
        #       - --disableImplicitSessions
        #       - --eval
        #       - "db.adminCommand('ping')"
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 6
        # readinessProbe:
        #   exec:
        #     command:
        #       - mongo
        #       - --disableImplicitSessions
        #       - --eval
        #       - "db.adminCommand('ping')"
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 6
        env:
        - name: MONGO_INITDB_DATABASE
          value: acme-db
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
          # valueFrom:
          #   secretKeyRef:
          #     name: mongo-creds
          #     key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: admin
          # valueFrom:
          #   secretKeyRef:
          #     name: mongo-creds
          #     key: password
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongodb-svc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: tcp
    name: tcp
  selector:
    app: mongo
  type: ClusterIP
