apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-retain
provisioner: nfs.csi.k8s.io
parameters:
# TODO: update the parameters below according to the real env
  server: 192.168.1.11
  share: /acme-data/
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
mountOptions:
  - nfsvers=4

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-delete
provisioner: nfs.csi.k8s.io
parameters:
# TODO: update the parameters below according to the real env
  server: 192.168.1.11
  share: /acme-data/
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4

---