apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client-retain
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
parameters:
# TODO: update the parameters below according to the real env
  server: 192.168.1.11
  share: /acme-data/
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
mountOptions:
  - nfsvers=4
